// POST valid new comment
POST http://localhost:3001/api/comments
content-type: application/json

{
  "content": "test comment",
  "name": "test comment author",
  "email": "testauthor@test.com",
  "postId": 1
}