// POST valid new user
POST http://localhost:3001/api/blogs
content-type: application/json

{
  "routeName": "blog-route",
  "title": "This is a blog title",
  "content": "HTML goes here",
  "media": {"name": "imageName", "url": "http://ImageURL", "caption": "An image"},
  "tags": ["personal", "blog", "nice"],
  "categoryId": 1
}