// POST valid new post
POST http://localhost:3001/api/posts
content-type: application/json

{
  "postSlug": "post-route11",
  "title": "This is a post title11",
  "content": "HTML goes here",
  "coverImage": {"urlSlug": "pagage.jpg", "altText": "An image"},
  "tags": [1],
  "categories": [1]
}