// UPDATE valid post
PUT http://localhost:3001/api/posts/post-route-3
content-type: application/json

{
  "postSlug": "post-route",
  "title": "This is a post title",
  "content": "HTML goes here",
  "media": {"name": "imageName", "url": "http://ImageURL", "caption": "An image"},
  "tags": ["personal", "post", "nice"],
  "categories": [1, 2]
}