###
// UPDATE valid category with valid data
PUT http://localhost:3001/api/categories/testcategory
content-type: application/json

{
  "categoryName": "former testcategory",
  "categorySlug": "former-testcategory",
  "description": "this is a description",
  "coverImage": {"urlSlug": "image.png", "altText": "Alt text"}

}

###
// UPDATE valid category with invalid data
PUT http://localhost:3001/api/categories/testcategory
content-type: application/json

{
  "categoryName": 400,
  "categorySlug": "testcategory",
  "description": "this is a description",
  "coverImage": {"urlSlug": "image.png", "altText": "Alt text"}
}

###
// UPDATE invalid category with valid data
PUT http://localhost:3001/api/categories/nonexisting
content-type: application/json

{
  "categoryName": "former testcategory",
  "categorySlug": "testcategory",
  "description": "this is a description",
  "coverImage": {"urlSlug": "image.png", "altText": "Alt text"}
}