// UPDATE valid post
PUT http://localhost:3001/api/posts/post-route
content-type: application/json

{
  "postSlug": "post-route2",
  "title": "This is a post title2",
  "content": "HTML goes here",
  "status": "trash",
  "coverImage": {"urlSlug": "http://ImageURL", "altText": "An image"},
  "tags": [1],
  "categories": [1, 2]
}