// POST valid new user
POST http://localhost:3001/api/users
content-type: application/json

{
  "username": "testUser",
  "password": "testPassword"
}


###
// POST invalid new user (missing password field)
POST http://localhost:3001/api/users
content-type: application/json

{
  "username": 7,
  "password": 2
}


###
// POST invalid new user (already existing username)
POST http://localhost:3001/api/users
content-type: application/json

{
  "username": "testUser",
  "password": "testPassword"
}